dist: bionic
addons:
  chrome: stable
before_install:
  - sudo systemctl stop postgresql
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
language: java
jdk:
  - openjdk11
services:
  - postgresql
addons:
  postgresql: "11.2"
before_script:
  - psql -U postgres -c "CREATE USER ${DB_USERNAME} WITH CREATEDB ENCRYPTED PASSWORD '${DB_PASSWORD}';"
  - psql -U postgres -c "CREATE DATABASE homer WITH OWNER = ${DB_USERNAME};"
  - export DISPLAY=:99.0
  - sudo systemctl start xvfb
  - sleep 5 # give xvfb some time to start
  - curl -L https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz  | tar zxv
  - sudo mv -f geckodriver /usr/local/share/
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
script:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=${COVERALLS_REPO_TOKEN} verify
cache:
  directories:
  - $HOME/.m2
